// Every word the visitor reads, in Swedish, as the dry run of 2026-10-04 showed Patric
// (docs/forms.md, "What the modal asks: the wizard").

export const TEXT = {
  close: 'Stäng',
  next: 'Fortsätt',
  send: 'Skicka',
  sending: 'Skickar…',
  skip: 'Hoppa över',
  done: 'Klart',
  back: 'Tillbaka',
  retry: 'Försök igen',
  loading: 'Hämtar…',
  title: {
    interest: 'Är du intresserad av bostaden?',
    viewing: 'Boka visning',
    lead: 'Ska du sälja din bostad?',
  },
  subtitleLead: 'Kostnadsfri värdering',
  chooseTime: 'Välj tid',
  noTimes: 'Det finns inga tider att boka just nu. Kontakta mäklaren så hjälper vi dig.',
  slotMissing: 'Välj en tid för att gå vidare.',
  placesLeft: (n: number): string => `${String(n)} ${n === 1 ? 'plats' : 'platser'} kvar`,
  full: 'Fullbokad',
  yourDetails: 'Dina uppgifter',
  firstName: 'Förnamn',
  lastName: 'Efternamn',
  phone: 'Mobil',
  email: 'E-post',
  message: 'Meddelande (valfritt)',
  consent: 'Jag samtycker till att mäklaren kontaktar mig och behandlar mina uppgifter enligt ',
  policy: 'integritetspolicyn',
  consentEnd: '.',
  personMissing: 'Fyll i alla fält och godkänn integritetspolicyn.',
  humanWaiting: 'Robotkontrollen är inte klar än. Vänta en liten stund och försök igen.',
  remembered: 'Vi minns dina uppgifter från förra gången i den här webbläsaren.',
  forget: 'Glöm mig',
  profileHeading: 'Söker du bostad?',
  profileText:
    'Berätta vad du letar efter, så får du tips om nya bostäder som passar. Du kan hoppa över det här steget.',
  stepOf: (at: number, of: number): string => `Steg ${String(at)} av ${String(of)} · valfritt`,
  roomsMin: 'Minst antal rum',
  areaMin: 'Minst boarea (kvm)',
  noRequirement: 'Inget krav',
  rooms: 'rum',
  sqm: 'kvm',
  areas: 'Områden',
  areasHintHome: 'Bostadens område är förvalt. Välj fler om du vill.',
  areasHintLead: 'Välj de områden du är intresserad av.',
  currentHome: 'Kontakta mig om min nuvarande bostad.',
  confirmed: {
    interest: (home: string): [string, string] => [
      'Din intresseanmälan är skickad',
      `${home}. Mäklaren hör av sig.`,
    ],
    viewing: (home: string, slot: string): [string, string] => [
      'Din plats är bokad',
      `${home} · ${slot}. Du får en bekräftelse från mäklaren.`,
    ],
    lead: (): [string, string] => [
      'Tack, vi hör av oss',
      'Kostnadsfri värdering. Mäklaren kontaktar dig.',
    ],
  },
  profileSent: ['Tack!', 'Du får tips om nya bostäder som passar det du söker.'] as const,
  profileSkipped: ['Klart', 'Ingen sökprofil skapades. Det du redan skickade är framme.'] as const,
  refused: 'Det gick tyvärr inte',
  refusedSlot: 'Någon hann före. Välj en annan tid.',
  failed: 'Det gick inte att skicka just nu',
  failedText: 'Mäklarsystemet svarade inte. Dina uppgifter finns kvar; försök igen om en stund.',
  tooMany: 'För många försök just nu. Vänta en stund och försök igen.',
  notHuman: 'Robotkontrollen gick inte igenom. Försök igen.',
  cannotLoad: 'Det gick inte att hämta formuläret. Ladda om sidan och försök igen.',
};
