// Generates acceptance/report.md from the acceptance criteria map and a real test run.
// The report is never edited by hand: if a criterion is green here, a named test proved it.
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const { criteria } = JSON.parse(readFileSync('acceptance/criteria.json', 'utf8'));

// Two runs: the default one, and the WordPress client suite, which has its own config because it
// needs a WordPress install (clients/wordpress/test/setup.sh).
const CONFIGS = ['vitest.config.ts', 'vitest.wordpress.config.ts'];

const results = new Map();
const outDir = mkdtempSync(join(tmpdir(), 'core-report-'));
for (const config of CONFIGS) {
  const resultsFile = join(outDir, `${config}.json`);
  try {
    execFileSync(
      'npx',
      ['vitest', 'run', '--config', config, '--reporter=json', `--outputFile=${resultsFile}`],
      { stdio: 'inherit' },
    );
  } catch {
    console.error(`tests under ${config} failed; the report below records that`);
  }
  for (const file of JSON.parse(readFileSync(resultsFile, 'utf8')).testResults) {
    for (const assertion of file.assertionResults)
      results.set(assertion.fullName, assertion.status);
  }
}

const PHASE_LABEL = {
  engine: 'engine (now)',
  clients: 'Phase 4, clients',
  'real-data': 'Phase 5, real data',
  adapters: 'Phase 6, adapters',
  deploy: 'needs the deployed platform',
};

const rows = criteria.map((criterion) => {
  const missing = criterion.tests.filter((name) => !results.has(name));
  const failed = criterion.tests.filter((name) => results.get(name) === 'failed');

  let status;
  if (criterion.tests.length === 0) status = '⏳ not yet';
  else if (missing.length > 0) status = '⚠️ test missing';
  else if (failed.length > 0) status = '❌ failing';
  else status = '✅ green';

  return { ...criterion, status, missing, failed };
});

const count = (status) => rows.filter((row) => row.status === status).length;

const lines = [
  '# Acceptance report',
  '',
  `Generated by \`npm run report\` on ${new Date().toISOString().slice(0, 10)}. Do not edit by hand.`,
  '',
  `**${count('✅ green')} of ${rows.length} criteria are green.** ${count('⏳ not yet')} wait on a later phase or on the platform; ` +
    `${count('⚠️ test missing')} name a test that no longer exists; ${count('❌ failing')} are failing.`,
  '',
  'The authoritative wording of each criterion is strategy §10, which amends SRS §13.',
  '',
  '| AC | Criterion | Status | Proved by |',
  '|---|---|---|---|',
];

for (const row of rows) {
  const proof =
    row.tests.length > 0
      ? row.tests.map((name) => `\`${name}\``).join('<br>')
      : `_${PHASE_LABEL[row.phase] ?? row.phase}_`;
  lines.push(`| ${row.ac} | ${row.title} | ${row.status} | ${proof} |`);
}

const notes = rows.filter((row) => row.note);
if (notes.length > 0) {
  lines.push('', '## Notes', '');
  for (const row of notes) lines.push(`- **AC ${row.ac}.** ${row.note}`);
}

const problems = rows.filter((row) => row.missing.length > 0 || row.failed.length > 0);
if (problems.length > 0) {
  lines.push('', '## Needs attention', '');
  for (const row of problems) {
    for (const name of row.missing) lines.push(`- AC ${row.ac}: no test named \`${name}\``);
    for (const name of row.failed) lines.push(`- AC ${row.ac}: \`${name}\` is failing`);
  }
}

writeFileSync('acceptance/report.md', `${lines.join('\n')}\n`);
console.log(`acceptance/report.md written: ${count('✅ green')} of ${rows.length} green`);
